# Generated by Django 3.1.5 on 2021-02-23 19:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import programming.models
import programming.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('short_name', models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only a-z and A-Z characters are allowed.')])),
                ('creation_date', models.DateTimeField(verbose_name='project creation date')),
                ('description', models.TextField(default='no description...')),
            ],
        ),
        migrations.CreateModel(
            name='ToolCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon', models.ImageField(blank=True, null=True, storage=programming.storage.OverwriteStorage, upload_to='icons/tools')),
                ('link', models.URLField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='programming.toolcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=programming.models.get_upload_path)),
                ('feature_card', models.BooleanField(default=False, verbose_name='Feature Project Card')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='programming.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='tools',
            field=models.ManyToManyField(blank=True, to='programming.Tool'),
        ),
    ]
